# -*- coding: utf-8 -*-
"""06 Python Break and Continue

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EN_NucR6SB0zPQtb1Zh8Ao6X4YKqDlnD

#Break and Continue

#Break

With the break statement we can stop the loop before it has looped through all the items:
"""

for i in range(10):  
  if (i==5):
    break                     #here the loop will exit completely after reaching 5
  print(i)

"""##Continue

With the continue statement we can stop ONLY the current iteration of the loop, and continue with the next:
"""

for i in range(10):  
  if (i==5):
    continue    
  print(i)                 #here the loop will skip only this iteration after reaching 5 and will continue as normal for the rest of it

"""##Do it yourself

* Given a word, print all the letters on a new line but stop once you encounter the letter 'a'

* Given a word, print all the letters on a new line but skip the letter 'a'

**Solution**

"""

#given
word='cocacola'

for i in word:
  if i=='a':
    break
  print(i)

print()

for i in word:
  if i=='a':
    continue
  print(i)