# -*- coding: utf-8 -*-
"""10 Python variable scope

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DHU9X9AMCnY7HfTw9goEfJUlip9ZOQwG

#Variable scope

if a variable is declared inside a function, then the variable is only accesible inside the function. Such a variable is called a **local variable**

Variables declared outside the functions are called **Global Variable**

**Example**

in the below code, x =300 is a global variable, whereas x=200 which is declared inside the function is a local variable.
"""

x=300

def variable():
  x=200
  print(x)

variable()    #here it will use the x inside the function(local variable)

print(x)      #since this is outside the function, it will use the global variable

"""if you have the same variable both inside and outside of a function, then we need to consider variable scope

if we want to make changes to a global varibale inside a function, we have to specify it with the global keyword.

**example**

lets specify the inside variable as global in the above example

"""

x=300

def variable():
  global x
  x=200
  print(x)

variable()    #here it will use the x inside the function(local variable)

print(x)      #since this is outside the function, it will use the global variable

"""#Do it yourself

* Create a variable name and assign it your name
* write a function to change the name to your best friends name

**Solution**
"""

name='Batman'

def namechange():
  global name
  name='Robin'

namechange()
print(name)