# -*- coding: utf-8 -*-
"""11 File Handling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTVvSGwxvSTLrMCB5WrW3A3_rUjfw02T

#File Handling

The key function for working with files in Python is the open() function.

##opening a file

The open() function takes two parameters; filename, and mode.

```
open( file, mode )
```

There are four different methods (modes) for opening a file:

```

"r" - Read - Default value. Opens a file for reading, error if the file does not exist

"a" - Append - Opens a file for appending, creates the file if it does not exist

"w" - Write - Opens a file for writing, creates the file if it does not exist

"x" - Create - Creates the specified file, returns an error if the file exists

```


In addition you can specify if the file should be handled as binary or text mode

```
"t" - Text - Default value. Text mode

"b" - Binary - Binary mode (e.g. images)
```

**example**
"""

words=open('words.txt','w')           # here when we use the 'w' mode, it will create a new file and open it for writting
words.close()                         # always close your files once your work is done

"""##writings to a file

once you open a file in python, there are 2 ways to write to a file. You can open the file in one of the following modes to get the desired result

`"a"` - Append - will append to the end of the file

`"w" `- Write - will overwrite any existing content


Then, to write to the file, simply use the .write() method

**Example**




"""

words=open('words.txt','w')           # here when we use the 'w' mode to write. if there is any content, it will replace it
words.write('This is the 1st sentence.')
words.close()  

#open the words.txt file on your computer and check whats inside

words=open('words.txt','a')           # here when we use the 'a' mode to append the new content. if there is any old content, it wont replace it
words.write('This is the 2nd sentence')
words.close() 

#open the words.txt file on your computer and check whats inside

words=open('words.txt','w')           # here when we use the 'w' mode to write the new content. if there is any old content, it will replace it
words.write('This will replace everything')
words.close() 

#open the words.txt file on your computer and check whats inside

"""##reading a file

to read an existing file, we use the'r' mode when opening the file. Then, we can use the .read() method to access the contents
"""

words = open("words.txt", "r")
text=words.read()
print(text)

"""** Try it yourself**

Do the following tasks:
* create a file and write 'The weather is very wonderful today'
* "add" the line, "it is very sunny outside"
* output the contents of the file

**Solution**
"""

f=open('file.txt','w')
f.write('The weather is very wonderful today. ')
f.close()

f=open('file.txt','a')
f.write('it is very sunny outside')
f.close()

f=open('file.txt','r')
print(f.read())