# -*- coding: utf-8 -*-
"""12 Python Modules

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8WY6XThbSqZL3iPxxgQe7JIgWXF3hFm

#Modules

#Importing Pre defined modules (libraries)

Many a times, we need some functionality which is not available in python by default. However python separately provides this functionality through modules. These are also referred to as libraries.

Sometimes these modules are not provided by python, but created by some user just like you and me, and shared with the rest of the world. These are referred to as 3rd party libraries.

To use any library in our code, we use the "import" keyword.

for example,

```
import library
```

if we want to refer to any function inside the library, we write the name of the library, followed by a dot and then the name of the function.


for example,
```
library.function()
```

**Alias for imports**

Sometimes the names of the libraries are long or difficult to write everytime we want to refer to its function. Therefore, to simplify things, we use a shorter alias for that function using the 'as' keyword. 

for example,


```
import library as lib

lib.function()
```

**importing a specific function from a library**

Sometimes we only want to use one or few functions from the many functions inside a library. As such, it is unwise to import the entire function just to use one function. Therefore, python allows us to only import a single function from a library using the 'from' keyword. 

In such a case, we can refer directly to the function without refering to the library

for example,



```
from library import function

function()
```

**Example**

lets create a for loop to print numbers from 0 to 10. lets add a delay of 1 sec after every number. to do this, we will need to import the time function and use its sleep function
"""

import time

for i in range(11):
  print(i)
  time.sleep(1)

#using an alias

import time as t

for i in range(11):
  print(i)
  t.sleep(1)

#importing only the sleep function

from time import sleep

for i in range(11):
  print(i)
  sleep(1)

"""#try it yourself

write the code to roll a dice and display heads or tails randomly. Use the choice function from random library
"""

from random import choice

dice=['heads','tails']

print(choice(dice))